"""auth tables (roles users refresh_tokens)

Revision ID: 6f4001226ab5
Revises: f9f62189349d
Create Date: 2026-01-14 15:50:21.351158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4001226ab5'
down_revision: Union[str, Sequence[str], None] = 'f9f62189349d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
